### ISSUE TITLE
chore: Linking error

### ISSUE THREAD

**Issue by JasonDsouza212** [bobbyy16/Hyper-List#3]
Upon clicking on the logo, it navigates to https://www.linkpicture.com/view.php?img=LPic64ad661c1b6861708777206, but it should be directed to other pages instead.

**Comment by bobbyy16** [comment]
Thanks for opening this issue @JasonDsouza212 . I wasn't aware of that. Can you change this link in anchor tag https://www.linkpicture.com/view.php?img=LPic64ad661c1b6861708777206 to /.  So that it goes to home page.

**Comment by bobbyy16** [comment]
Hey, @geraldopmj you have to create pull request to this repo's main branch.

**Comment by bobbyy16** [comment]
Also mention the issue number while creating pull request.

**Comment by bobbyy16** [comment]
changes are done
